export const players = [
  {
    id: 1,
    name: "LeBron James",
    team: "Los Angeles Lakers",
    position: "SF",
    ppg: 25.5,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/lebron.webp",
  },
  {
    id: 2,
    name: "Stephen Curry",
    team: "Golden State Warriors",
    position: "PG",
    ppg: 28.1,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/steph.webp",
  },
  {
    id: 3,
    name: "Kevin Durant",
    team: "Phoenix Suns",
    position: "SF",
    ppg: 29.7,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/kd.webp",
  },
  {
    id: 4,
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    position: "PF",
    ppg: 30.1,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/giannis.avif",
  },
  {
    id: 5,
    name: "Luka Dončić",
    team: "Dallas Mavericks",
    position: "PG",
    ppg: 30.3,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/luka.avif",
  },
  {
    id: 6,
    name: "Joel Embiid",
    team: "Philadelphia 76ers",
    position: "C",
    ppg: 33.1,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/embid.avif",
  },
  {
    id: 7,
    name: "Nikola Jokić",
    team: "Denver Nuggets",
    position: "C",
    ppg: 25.6,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/joker.avif",
  },
  {
    id: 8,
    name: "Kawhi Leonard",
    team: "Los Angeles Clippers",
    position: "SF",
    ppg: 22.5,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/leonard.avif",
  },
  {
    id: 9,
    name: "Jayson Tatum",
    team: "Boston Celtics",
    position: "SF",
    ppg: 26.8,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/tatum.webp",
  },
  {
    id: 10,
    name: "Damian Lillard",
    team: "Milwaukee Bucks",
    position: "PG",
    ppg: 27.9,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/lillard.avif",
  },
  {
    id: 11,
    name: "Jimmy Butler",
    team: "Miami Heat",
    position: "SF",
    ppg: 23.3,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/jimmy.webp",
  },
  {
    id: 12,
    name: "Anthony Davis",
    team: "Los Angeles Lakers",
    position: "PF",
    ppg: 22.9,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/davis.webp",
  },
  {
    id: 13,
    name: "Kyrie Irving",
    team: "Dallas Mavericks",
    position: "PG",
    ppg: 27.1,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/kyrie.avif",
  },
  {
    id: 14,
    name: "James Harden",
    team: "Philadelphia 76ers",
    position: "SG",
    ppg: 21.7,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/harden.avif",
  },
  {
    id: 15,
    name: "Zion Williamson",
    team: "New Orleans Pelicans",
    position: "PF",
    ppg: 26.5,
    imageUrl: "https://github.com/utsavarch/task1/blob/main/public/players/zion.avif",
  },
];
